

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LR6_odata
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class WSBGSEntities : DbContext
{
    public WSBGSEntities()
        : base("name=WSBGSEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Note> Notes { get; set; }

    public virtual DbSet<Student> Students { get; set; }

}

}

