//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LR4_check_sum_method.SimplexService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace="http://BGS/")]
    [System.SerializableAttribute()]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sField;
        
        private int kField;
        
        private float fField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string s {
            get {
                return this.sField;
            }
            set {
                if ((object.ReferenceEquals(this.sField, value) != true)) {
                    this.sField = value;
                    this.RaisePropertyChanged("s");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int k {
            get {
                return this.kField;
            }
            set {
                if ((this.kField.Equals(value) != true)) {
                    this.kField = value;
                    this.RaisePropertyChanged("k");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float f {
            get {
                return this.fField;
            }
            set {
                if ((this.fField.Equals(value) != true)) {
                    this.fField = value;
                    this.RaisePropertyChanged("f");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://BGS/", ConfigurationName="SimplexService.SimplexSoap")]
    public interface SimplexSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Sum_1) сообщения Sum_1 не соответствует значению по умолчанию (Add).
        [System.ServiceModel.OperationContractAttribute(Action="http://BGS/Sum_1", ReplyAction="*")]
        LR4_check_sum_method.SimplexService.Sum_11 Add(LR4_check_sum_method.SimplexService.Sum_1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BGS/Sum_1", ReplyAction="*")]
        System.Threading.Tasks.Task<LR4_check_sum_method.SimplexService.Sum_11> AddAsync(LR4_check_sum_method.SimplexService.Sum_1 request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Sum_2) сообщения Sum_2 не соответствует значению по умолчанию (Concat).
        [System.ServiceModel.OperationContractAttribute(Action="http://BGS/Sum_2", ReplyAction="*")]
        LR4_check_sum_method.SimplexService.Sum_21 Concat(LR4_check_sum_method.SimplexService.Sum_2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BGS/Sum_2", ReplyAction="*")]
        System.Threading.Tasks.Task<LR4_check_sum_method.SimplexService.Sum_21> ConcatAsync(LR4_check_sum_method.SimplexService.Sum_2 request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Sum_3) сообщения Sum_3 не соответствует значению по умолчанию (Sum).
        [System.ServiceModel.OperationContractAttribute(Action="http://BGS/Sum_3", ReplyAction="*")]
        LR4_check_sum_method.SimplexService.Sum_31 Sum(LR4_check_sum_method.SimplexService.Sum_3 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BGS/Sum_3", ReplyAction="*")]
        System.Threading.Tasks.Task<LR4_check_sum_method.SimplexService.Sum_31> SumAsync(LR4_check_sum_method.SimplexService.Sum_3 request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Sum_4) сообщения Sum_4 не соответствует значению по умолчанию (Adds).
        [System.ServiceModel.OperationContractAttribute(Action="http://BGS/Sum_4", ReplyAction="*")]
        LR4_check_sum_method.SimplexService.Sum_41 Adds(LR4_check_sum_method.SimplexService.Sum_4 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BGS/Sum_4", ReplyAction="*")]
        System.Threading.Tasks.Task<LR4_check_sum_method.SimplexService.Sum_41> AddsAsync(LR4_check_sum_method.SimplexService.Sum_4 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum_1", WrapperNamespace="http://BGS/", IsWrapped=true)]
    public partial class Sum_1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BGS/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BGS/", Order=1)]
        public int y;
        
        public Sum_1() {
        }
        
        public Sum_1(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum_1Response", WrapperNamespace="http://BGS/", IsWrapped=true)]
    public partial class Sum_11 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BGS/", Order=0)]
        public int Sum_1Result;
        
        public Sum_11() {
        }
        
        public Sum_11(int Sum_1Result) {
            this.Sum_1Result = Sum_1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum_2", WrapperNamespace="http://BGS/", IsWrapped=true)]
    public partial class Sum_2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BGS/", Order=0)]
        public string s;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BGS/", Order=1)]
        public double d;
        
        public Sum_2() {
        }
        
        public Sum_2(string s, double d) {
            this.s = s;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum_2Response", WrapperNamespace="http://BGS/", IsWrapped=true)]
    public partial class Sum_21 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BGS/", Order=0)]
        public string Sum_2Result;
        
        public Sum_21() {
        }
        
        public Sum_21(string Sum_2Result) {
            this.Sum_2Result = Sum_2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum_3", WrapperNamespace="http://BGS/", IsWrapped=true)]
    public partial class Sum_3 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BGS/", Order=0)]
        public LR4_check_sum_method.SimplexService.A a1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BGS/", Order=1)]
        public LR4_check_sum_method.SimplexService.A a2;
        
        public Sum_3() {
        }
        
        public Sum_3(LR4_check_sum_method.SimplexService.A a1, LR4_check_sum_method.SimplexService.A a2) {
            this.a1 = a1;
            this.a2 = a2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum_3Response", WrapperNamespace="http://BGS/", IsWrapped=true)]
    public partial class Sum_31 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BGS/", Order=0)]
        public LR4_check_sum_method.SimplexService.A Sum_3Result;
        
        public Sum_31() {
        }
        
        public Sum_31(LR4_check_sum_method.SimplexService.A Sum_3Result) {
            this.Sum_3Result = Sum_3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum_4", WrapperNamespace="http://BGS/", IsWrapped=true)]
    public partial class Sum_4 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BGS/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BGS/", Order=1)]
        public int y;
        
        public Sum_4() {
        }
        
        public Sum_4(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Sum_4Response", WrapperNamespace="http://BGS/", IsWrapped=true)]
    public partial class Sum_41 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BGS/", Order=0)]
        public int Sum_4Result;
        
        public Sum_41() {
        }
        
        public Sum_41(int Sum_4Result) {
            this.Sum_4Result = Sum_4Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimplexSoapChannel : LR4_check_sum_method.SimplexService.SimplexSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplexSoapClient : System.ServiceModel.ClientBase<LR4_check_sum_method.SimplexService.SimplexSoap>, LR4_check_sum_method.SimplexService.SimplexSoap {
        
        public SimplexSoapClient() {
        }
        
        public SimplexSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LR4_check_sum_method.SimplexService.Sum_11 LR4_check_sum_method.SimplexService.SimplexSoap.Add(LR4_check_sum_method.SimplexService.Sum_1 request) {
            return base.Channel.Add(request);
        }
        
        public int Add(int x, int y) {
            LR4_check_sum_method.SimplexService.Sum_1 inValue = new LR4_check_sum_method.SimplexService.Sum_1();
            inValue.x = x;
            inValue.y = y;
            LR4_check_sum_method.SimplexService.Sum_11 retVal = ((LR4_check_sum_method.SimplexService.SimplexSoap)(this)).Add(inValue);
            return retVal.Sum_1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LR4_check_sum_method.SimplexService.Sum_11> LR4_check_sum_method.SimplexService.SimplexSoap.AddAsync(LR4_check_sum_method.SimplexService.Sum_1 request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<LR4_check_sum_method.SimplexService.Sum_11> AddAsync(int x, int y) {
            LR4_check_sum_method.SimplexService.Sum_1 inValue = new LR4_check_sum_method.SimplexService.Sum_1();
            inValue.x = x;
            inValue.y = y;
            return ((LR4_check_sum_method.SimplexService.SimplexSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LR4_check_sum_method.SimplexService.Sum_21 LR4_check_sum_method.SimplexService.SimplexSoap.Concat(LR4_check_sum_method.SimplexService.Sum_2 request) {
            return base.Channel.Concat(request);
        }
        
        public string Concat(string s, double d) {
            LR4_check_sum_method.SimplexService.Sum_2 inValue = new LR4_check_sum_method.SimplexService.Sum_2();
            inValue.s = s;
            inValue.d = d;
            LR4_check_sum_method.SimplexService.Sum_21 retVal = ((LR4_check_sum_method.SimplexService.SimplexSoap)(this)).Concat(inValue);
            return retVal.Sum_2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LR4_check_sum_method.SimplexService.Sum_21> LR4_check_sum_method.SimplexService.SimplexSoap.ConcatAsync(LR4_check_sum_method.SimplexService.Sum_2 request) {
            return base.Channel.ConcatAsync(request);
        }
        
        public System.Threading.Tasks.Task<LR4_check_sum_method.SimplexService.Sum_21> ConcatAsync(string s, double d) {
            LR4_check_sum_method.SimplexService.Sum_2 inValue = new LR4_check_sum_method.SimplexService.Sum_2();
            inValue.s = s;
            inValue.d = d;
            return ((LR4_check_sum_method.SimplexService.SimplexSoap)(this)).ConcatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LR4_check_sum_method.SimplexService.Sum_31 LR4_check_sum_method.SimplexService.SimplexSoap.Sum(LR4_check_sum_method.SimplexService.Sum_3 request) {
            return base.Channel.Sum(request);
        }
        
        public LR4_check_sum_method.SimplexService.A Sum(LR4_check_sum_method.SimplexService.A a1, LR4_check_sum_method.SimplexService.A a2) {
            LR4_check_sum_method.SimplexService.Sum_3 inValue = new LR4_check_sum_method.SimplexService.Sum_3();
            inValue.a1 = a1;
            inValue.a2 = a2;
            LR4_check_sum_method.SimplexService.Sum_31 retVal = ((LR4_check_sum_method.SimplexService.SimplexSoap)(this)).Sum(inValue);
            return retVal.Sum_3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LR4_check_sum_method.SimplexService.Sum_31> LR4_check_sum_method.SimplexService.SimplexSoap.SumAsync(LR4_check_sum_method.SimplexService.Sum_3 request) {
            return base.Channel.SumAsync(request);
        }
        
        public System.Threading.Tasks.Task<LR4_check_sum_method.SimplexService.Sum_31> SumAsync(LR4_check_sum_method.SimplexService.A a1, LR4_check_sum_method.SimplexService.A a2) {
            LR4_check_sum_method.SimplexService.Sum_3 inValue = new LR4_check_sum_method.SimplexService.Sum_3();
            inValue.a1 = a1;
            inValue.a2 = a2;
            return ((LR4_check_sum_method.SimplexService.SimplexSoap)(this)).SumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LR4_check_sum_method.SimplexService.Sum_41 LR4_check_sum_method.SimplexService.SimplexSoap.Adds(LR4_check_sum_method.SimplexService.Sum_4 request) {
            return base.Channel.Adds(request);
        }
        
        public int Adds(int x, int y) {
            LR4_check_sum_method.SimplexService.Sum_4 inValue = new LR4_check_sum_method.SimplexService.Sum_4();
            inValue.x = x;
            inValue.y = y;
            LR4_check_sum_method.SimplexService.Sum_41 retVal = ((LR4_check_sum_method.SimplexService.SimplexSoap)(this)).Adds(inValue);
            return retVal.Sum_4Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LR4_check_sum_method.SimplexService.Sum_41> LR4_check_sum_method.SimplexService.SimplexSoap.AddsAsync(LR4_check_sum_method.SimplexService.Sum_4 request) {
            return base.Channel.AddsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LR4_check_sum_method.SimplexService.Sum_41> AddsAsync(int x, int y) {
            LR4_check_sum_method.SimplexService.Sum_4 inValue = new LR4_check_sum_method.SimplexService.Sum_4();
            inValue.x = x;
            inValue.y = y;
            return ((LR4_check_sum_method.SimplexService.SimplexSoap)(this)).AddsAsync(inValue);
        }
    }
}
